name = "nextjs-starter"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Configure environment variables
[vars]
# Add your environment variables here if needed
# NEXT_PUBLIC_BASE_URL = "https://your-domain.com"

# You can add bindings for KV, D1, R2, etc. if needed
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-id"
