[build]
command = "cp cloudflare-package.json package.json && npm install --legacy-peer-deps && npm run build"
output_directory = ".vercel/output/static"
build_directory = ".vercel/output/static"

[build.environment]
NODE_VERSION = "18"
CLOUDFLARE = "true"
NPM_FLAGS = "--legacy-peer-deps"

[site]
bucket = ".vercel/output/static"

[env.production]
CLOUDFLARE = "true"
NODE_ENV = "production"
